adding test on yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -63,6 +63,25 @@ jobs:
         cd ${{ matrix.build_dir }}
         cmake --build . --config Release
 
+    - name: Run Program (${{ matrix.compiler_name }})
+        shell: bash
+        run: |
+        cd ${{ matrix.build_dir }}
+        if [ "${{ matrix.os }}" != "windows-latest" ]; then
+          ./your_program_executable
+        else
+          Release\your_program_executable.exe
+        fi
+
+    - name: Verify Output
+      shell: bash
+      run: |
+        OUTPUT=$(./your_program_executable)
+        if [[ "$OUTPUT" != "Expected Output" ]]; then
+          echo "Error: Unexpected output!"
+        exit 1
+        fi
+
     - name: Run tests (${{ matrix.compiler_name }})
       shell: bash
       run: |
